---
title: "Lab_13"
author: "Matthew Copeland"
date: "April 17, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(cowplot)
library(stringr)
library(gapminder)
```
### Overall Question: What is world health like in Europe? Also Which continent should we focus our health aid spending on?

#### Specific Question Kelsey
What is life Expectancy like in Europe?
```{r}
library(tidyverse)
library(dplyr)
library(lubridate)
library(stringr)
library(gapminder)
library(forcats)
library(cowplot)
read_csv(life_expectancy_years1.csv)
gapminder2 <- gapminder 



life_exp_year <- function(perms = 1000, continent1,year1, n1 ){


  mean_mat <- matrix(0,1000,1)
  for (i in c(1:perms))
  {
    cont1 <- gapminder2 %>% filter(continent == continent1, year ==year1 ) %>% select(lifeExp)
    cont2 <- gapminder2 %>% filter(year ==year1 ) %>% select(lifeExp)
    rsamp <- sample(cont1$lifeExp, n1, replace = FALSE)
    other <- sample(cont2$lifeExp, length(cont2$lifeExp)-n1, replace = FALSE)

    A <- mean(rsamp)
    B <- mean(other)
    mean_mat[[i]] <- (A-B)
  }
  return(mean_mat)
}
rsample <- as.tibble(life_exp_year(perms = 1000, continent1 = "Asia", year1 = 2007, n1=10))

cont3 <- gapminder2 %>% filter(continent == "Europe", year ==2007 ) %>% select(lifeExp)
cont4 <- gapminder2 %>% filter( year ==2007 ) %>% select(lifeExp)
life_ex1 <- summary(cont3$lifeExp)
life_ex2 <- summary(cont4$lifeExp)
diff <- median(life_ex1)- median(life_ex2)
std <- sqrt((sd(cont3$lifeExp))^2/length(cont3$lifeExp) + (sd(cont4$lifeExp))^2/length(cont4$lifeExp))
z_score <- diff/std
z_score
#So our p-value is .1111 so statistically significant at p>.11 for Asian countries life expectancy
ggplot(rsample, aes(x=V1 ))+geom_histogram()+
  xlab("Means")+
  geom_vline(xintercept = diff, color = "red", size = .3)+
  ylab("Number")+
  ggtitle("Difference in Means in Life Expectancy")
cont2 <- gapminder2 %>% filter(year ==2007 ) %>% select(lifeExp)
```





